# // FILE PATH FOR DATA // #

TEAM_PATH = 'GAME DATA\\TEAMS\\'
TEXT_PATH = 'GAME DATA\\TEXT_DESCRIPTIONS\\'
HIT_LOCS = 'GAME DATA\\HIT_LOCATIONS\\'
SCENARIO_DATA = 'GAME DATA\\SCENE_PROBS\\'
LEAGUE_HIT = 'GAME DATA\\TEAMS\\LGD\\LGD_HIT.csv'
LEAGUE_PSL = 'GAME DATA\\TEAMS\\LGD\\LGD_PSL.csv'
LEAGUE_PFR = 'GAME DATA\\TEAMS\\LGD\\LGD_PFR.csv'
PBP_SEQUENCE = 'GAME DATA\\PITCH SEQUENCES\\'